name: Build & Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  tcp-lab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ${{ github.job }}
        run: |
          docker run --rm -v $(pwd):/app ghcr.io/peaceiris/mdbook build /app
          mv book ${{ github.job }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: ${{ github.job }}/${{ github.job }}
  
  aggregate:
    runs-on: ubuntu-latest
    needs: [tcp-lab]
    steps:
      # - run: mkdir _site
      - uses: actions/download-artifact@v3
        with:
          path: _site
      - run: tree
      - uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: aggregate
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
